sudo: required
services:
  - docker

before_install:
  - docker build -t eb0x/docker-react-travis-aws-playground -f Dockerfile.dev .

script: 
  - docker run -c CI=true eb0x94/docker-react-travis-aws-playground npm run test
